name: internStack
description: Australian Software Internships Listing
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_core: ^0.2.5
  firebase_analytics: ^1.0.4
  cloud_firestore: ^0.8.2
  url_launcher: ^4.0.3
  share: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
      - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/PoppinsFont/Poppins-Thin.ttf
          weight: 100
        - asset: assets/PoppinsFont/Poppins-Light.ttf
          weight: 300
        - asset: assets/PoppinsFont/Poppins-Regular.ttf
          weight: 400
        - asset: assets/PoppinsFont/Poppins-Medium.ttf
          weight: 500
        - asset: assets/PoppinsFont/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/PoppinsFont/Poppins-Bold.ttf
          weight: 700