version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: 
          name: Flutter Doctor
          command: flutter doctor
      - run: 
          name: Flutter Build APK
          command: flutter -v build apk
