version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      
      - run: 
          name: Flutter Doctor
          command: flutter doctor

      - run:
          name: Flutter Accept Android Licenses
          command: yes | flutter doctor --android-licenses || if [ $? -ne '141' ]; then exit $?; fi; 

      - run:
          name: Android Keystore Setup
          command: .circleci/keystore.sh

      - run: 
          name: Flutter Build APK
          command: flutter -v build apk --build-name=$CIRCLE_TAG --build-number=$CIRCLE_BUILD_NUM

      - store_artifacts:
          path: ./build/app/outputs/apk/release/app-release.apk
          destination: .apk/internstack.apk

workflows:
  version: 2
  build-n-publish:
    jobs:
    - build:
        filters:
          tags:
            only: /^v.*/