version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter:1.0.0
    steps:
      - checkout

      - run: 
          name: Flutter Doctor
          command: flutter doctor

      - run:
          name: Flutter Accept Android Licenses
          command: echo y | flutter doctor --android-licenses

      - run: 
          name: Flutter Build APK
          command: flutter -v build apk

      - store_artifacts:
          path: ./build/app/outputs/apk/release/app-release.apk
